name: Scrape daily

on:
  schedule:
    - cron: '0 2 * * *'  # Ogni giorno alle 3:00 italiane
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install system deps
        run: |
          sudo apt-get update
          sudo apt-get install -y tesseract-ocr libtiff5 libjpeg62-turbo libopenjp2-7 poppler-utils
      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt
          python -m playwright install --with-deps
      - name: Run scraper
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          python backend/scraper/scraper_multi.py
